import temp from "../assets/temporary-image.png";

export const LIST_DATA = [
  {
    id: 1,
    title: "블루베리 비빔밥",
    img: temp,
    likes: 100,
    bookmark: true,
    isLiked: true,
  },
  {
    id: 2,
    title: "고추장 마요 달걀밥",
    img: temp,
    likes: 97,
    bookmark: false,
    isLiked: true,
  },
  {
    id: 3,
    title: "두바이 쫀득쿠키",
    img: temp,
    likes: 44,
    bookmark: false,
    isLiked: true,
  },
  {
    id: 4,
    title: "허니버터 감자 핫도그",
    img: temp,
    likes: 10,
    bookmark: true,
    isLiked: true,
  },
  {
    id: 5,
    title: "로제 마라샹궈",
    img: temp,
    likes: 0,
    bookmark: false,
    isLiked: true,
  },
  {
    id: 6,
    title: "우삼겹 차돌 마라탕",
    img: temp,
    likes: 1,
    bookmark: false,
    isLiked: true,
  },
  {
    id: 7,
    title: "버터 갈릭 감자튀김",
    img: temp,
    likes: 88,
    bookmark: false,
    isLiked: true,
  },
  {
    id: 8,
    title: "크루아상 샌드위치",
    img: temp,
    likes: 10,
    bookmark: true,
    isLiked: true,
  },
  {
    id: 9,
    title: "아이스바닐라라떼",
    img: temp,
    likes: 0,
    bookmark: true,
    isLiked: true,
  },
  {
    id: 10,
    title: "간장계란밥",
    img: temp,
    likes: 7,
    bookmark: true,
    isLiked: true,
  },
  {
    id: 11,
    title: "블루베리 비빔밥",
    img: temp,
    likes: 100,
    bookmark: false,
    isLiked: true,
  },
  {
    id: 12,
    title: "블루베리 비빔밥",
    img: temp,
    likes: 100,
    bookmark: false,
    isLiked: true,
  },
  {
    id: 13,
    title: "블루베리 비빔밥",
    img: temp,
    likes: 100,
    bookmark: false,
    isLiked: true,
  },
  {
    id: 14,
    title: "블루베리 비빔밥",
    img: temp,
    likes: 100,
    bookmark: false,
    isLiked: true,
  },
  {
    id: 15,
    title: "블루베리 비빔밥",
    img: temp,
    likes: 100,
    bookmark: false,
    isLiked: true,
  },
  {
    id: 16,
    title: "블루베리 비빔밥",
    img: temp,
    likes: 100,
    bookmark: false,
    isLiked: true,
  },
  {
    id: 17,
    title: "블루베리 비빔밥",
    img: temp,
    likes: 100,
    bookmark: false,
    isLiked: true,
  },
  {
    id: 18,
    title: "블루베리 비빔밥",
    img: temp,
    likes: 100,
    bookmark: false,
    isLiked: true,
  },
  {
    id: 19,
    title: "블루베리 비빔밥",
    img: temp,
    likes: 100,
    bookmark: false,
    isLiked: true,
  },
  {
    id: 20,
    title: "블루베리 비빔밥",
    img: temp,
    likes: 100,
    bookmark: false,
    isLiked: true,
  },
];
